name: hooks_rxget
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  rxget:
    git:
      url: https://github.com/sugithGit/rxget.git
      path: packages/rxget
      ref: c187c1379e6544917dc8c8a437b7aa60c0175715

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
