builders:
  rxget_state:
    import: "package:rxget_generator/builder.dart"
    builder_factories: ["rxgetStateBuilder"]
    build_extensions: {".dart": [".rxget.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
